### ISSUE TITLE
latest dm4 bundles are now available from Felix OBR

### ISSUE THREAD

**Issue by pderop** [mnlipp/osgi-getting-started#1]
Hello Michael;

I found from google your interesting osgi introduction, especially I found [1] where you mentioned that  the latest dm4 bundles were not available from the Felix OBR in [2].

so, just to say that I just pushed the (overdue) dm4 bundles to the felix OBR, and now from bndtools, if you declare for example the following:

-plugin.5.FELIX: \
	aQute.bnd.deployer.repository.FixedIndexedRepo; \
		name=FELIX; \
		cache=${workspace}/cnf/cache; \
		locations=http://felix.apache.org/obr/releases.xml

Then you will be able to use from any buildpath the following dm4 bundles:

org.apache.felix.dependencymanager;version=4.4.0
org.apache.felix.dependencymanager.shell;version=4.0.5
org.apache.felix.dependencymanager.runtime;version=4.0.4
org.apache.felix.dependencymanager.lambda;version=1.1.0

Regarding DM annotations, you can also possibly set the following buildpath in cnf/build.bnd:
(in case you don't want to include the dm4 annotation plugin in cnf/local):

-pluginpath: \
        ${workspace}/cnf/cache/org.apache.dependencymanager.annotation-4.2.0.jar;url=http://repo1.maven.org/maven2/org/apache/felix/org.apache.felix.dependencymanager.annotation/4.2.0/org.apache.felix.dependencymanager.annotation-4.2.0.jar

and then the dm annotation plugin can be declared like this:

-plugin: org.apache.felix.dm.annotation.plugin.bnd.AnnotationPlugin

thanks you;
Pierre

[1] http://mnlipp.github.io/osgi-getting-started/ServiceComponent.html
[2] http://felix.apache.org/obr/releases.xml

**Comment by mnlipp** [comment]
Thanks for the feedback! I'll update the description soon.
